version: '3.8'

services:
  app:
    build: .
    ports:
      - "5000:5000"
    environment:
      - FLASK_ENV=development
      - DATABASE_URL=sqlite:///affiliate_marketing.db
      - SECRET_KEY=your-secret-key-here
      - X_API_KEY=your-x-api-key
      - X_API_SECRET=your-x-api-secret
      - X_ACCESS_TOKEN=your-x-access-token
      - X_ACCESS_TOKEN_SECRET=your-x-access-token-secret
    volumes:
      - ./backend:/app
      - ./data:/app/data
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/api/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s

  # Optional: Add a database service for production
  # postgres:
  #   image: postgres:15-alpine
  #   environment:
  #     POSTGRES_DB: affiliate_marketing
  #     POSTGRES_USER: postgres
  #     POSTGRES_PASSWORD: password
  #   volumes:
  #     - postgres_data:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"

# volumes:
#   postgres_data:
